jib 1차 속도테스트

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -21,21 +21,21 @@ jobs:
           distribution: 'temurin'
 
 
-      - name: Cache Gradle packages
-        uses: actions/cache@v3
-        with:
-          path: ~/.gradle/caches
-          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
-          restore-keys: |
-            ${{ runner.os }}-gradle-
+#      - name: Cache Gradle packages
+#        uses: actions/cache@v3
+#        with:
+#          path: ~/.gradle/caches
+#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
+#          restore-keys: |
+#            ${{ runner.os }}-gradle-
 
-      - name: Cache Docker layers
-        uses: actions/cache@v3
-        with:
-          path: /home/runner/.cache/docker
-          key: ${{ runner.os }}-docker-${{ github.sha }}
-          restore-keys: |
-            ${{ runner.os }}-docker-
+#      - name: Cache Docker layers
+#        uses: actions/cache@v3
+#        with:
+#          path: /home/runner/.cache/docker
+#          key: ${{ runner.os }}-docker-${{ github.sha }}
+#          restore-keys: |
+#            ${{ runner.os }}-docker-
 
       - name: Docker Hub login
         uses: docker/login-action@v2
@@ -48,25 +48,25 @@ jobs:
 
 
 
-  deploy:
-    runs-on: ubuntu-latest
-    needs: build
-
-    steps:
-      - name: SSH to EC2
-        uses: appleboy/ssh-action@v0.1.10
-        with:
-          host: ${{ secrets.EC2_HOST }}
-          username: ubuntu
-          key: ${{ secrets.EC2_SSH_KEY }}
-          port: 22
-          script: |
-            cd ~/want
-            if ! type docker > /dev/null; then
-              sudo snap install docker || echo "docker install failed"
-            else
-              echo "docker is already installed"
-            fi
-            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
-            chmod +x deploy.sh
-            ./deploy.sh jsangmin00/want_project:latest
+#  deploy:
+#    runs-on: ubuntu-latest
+#    needs: build
+#
+#    steps:
+#      - name: SSH to EC2
+#        uses: appleboy/ssh-action@v0.1.10
+#        with:
+#          host: ${{ secrets.EC2_HOST }}
+#          username: ubuntu
+#          key: ${{ secrets.EC2_SSH_KEY }}
+#          port: 22
+#          script: |
+#            cd ~/want
+#            if ! type docker > /dev/null; then
+#              sudo snap install docker || echo "docker install failed"
+#            else
+#              echo "docker is already installed"
+#            fi
+#            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
+#            chmod +x deploy.sh
+#            ./deploy.sh jsangmin00/want_project:latest
